# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [40]:

import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode == 'zeros':
        return np.zeros(shape)
    elif mode == 'ones':
        return np.ones(shape)
    elif mode == 'full':
        return np.full(shape, value)
    elif mode == 'identity':
        size = shape[0] if isinstance(shape, (tuple, list)) else shape
        return np.eye(size)
    else:
         raise ValueError(f"Unknown mode: {mode}")
    
    pass

In [42]:
print(array_factory('ones',(4,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [64]:
def secure_reshape_and_stack(data1, data2, new_shape):

    # 1. validates and converts inputs to NumPy arrays.
    # 2. Reshapes the first dataset to a specific dimension.
    # 3. Vertically stacks both datasets into one matrix.

    try:
        # Convert inputs to numpy arrays
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        print("array 1")
        print("array 1: " + str(arr1))

        print("array 2")
        print("array 2: " + str(arr2))

        # Reshape the first dataset to new_shape
        reshaped_arr1 = np.array(arr1).reshape(new_shape)
        reshaped_arr2 = np.array(arr2).reshape(new_shape)

        print("reshaped_arr1")
        print(reshaped_arr1)

        print("reshaped_arr2")
        print(reshaped_arr2)

        # Vertical stacking (vstack)
        # Both arrays must have the same number of columns

        combined_dataset = np.vstack(
            (reshaped_arr1, reshaped_arr2)
        )

        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match
        # or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")

In [65]:
secure_reshape_and_stack([1,2,3,4,5,6,7,8], [9,10,11,12,13,14,15,16], (2,4))

array 1
array 1: [1 2 3 4 5 6 7 8]
array 2
array 2: [ 9 10 11 12 13 14 15 16]
reshaped_arr1
[[1 2 3 4]
 [5 6 7 8]]
reshaped_arr2
[[ 9 10 11 12]
 [13 14 15 16]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [81]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    arr = np.array(arr)

    # 2. Define the condition: elementwise comparison 
    # This creates a Boolean numpy array 
    condition = arr >= threshold
    
    # 3. Apply Modification using np.where() 
    # np.where(condition, value_if_true, value_if_false)
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr

TestCase

In [85]:
# Regional Branch A (Flat sales data)
branch_a = np.array(branch_a).reshape(2, 3)

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = apply_threshold(branch_a, branch_b, -20)
print(final_report)
# Resulting shape: (4, 3)

[[1 2 3]
 [4 5 6]]


In [84]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])